.PHONY: all
all:
	$(MAKE) -C StructTact
	$(MAKE) -C SimpleDS
	$(MAKE) -C InfSeqExt
	$(MAKE) -C cheerios
	$(MAKE) -C verdi

.PHONY: clean
clean:
	$(MAKE) -C StructTact clean
	$(MAKE) -C SimpleDS clean
	$(MAKE) -C InfSeqExt clean
	$(MAKE) -C cheerios clean
	$(MAKE) -C verdi clean
